spring:
  application:
    name: service-content
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_content
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
server:
  port: 10004
mybatis:
  type-aliases-package: com.itheima.changgou.content.pojo
  mapper-locations: classptah:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.itheima.changgou.content.dao: debug
