spring:
  application:
    name: service_canal
  redis:
    host: 192.168.211.132
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
server:
  port: 10003
canal:
  client:
    instances:
      example:
        host: 192.168.211.132
        port: 11111